import 'package:flutter/widgets.dart';

import 'flutter_icon_data.dart';

/// A class that holds static variables representing all Icons under EvilIcons
///
/// http://evil-icons.io
class EvilIcons {
  EvilIcons._();
  static const IconData archive = FlutterIconData.evilIcons(61696);
  static const IconData arrowDown = FlutterIconData.evilIcons(61697);
  static const IconData arrowLeft = FlutterIconData.evilIcons(61698);
  static const IconData arrowRight = FlutterIconData.evilIcons(61699);
  static const IconData arrowUp = FlutterIconData.evilIcons(61700);
  static const IconData bell = FlutterIconData.evilIcons(61701);
  static const IconData calendar = FlutterIconData.evilIcons(61702);
  static const IconData camera = FlutterIconData.evilIcons(61703);
  static const IconData cart = FlutterIconData.evilIcons(61704);
  static const IconData chart = FlutterIconData.evilIcons(61705);
  static const IconData check = FlutterIconData.evilIcons(61706);
  static const IconData chevronDown = FlutterIconData.evilIcons(61707);
  static const IconData chevronLeft = FlutterIconData.evilIcons(61708);
  static const IconData chevronRight = FlutterIconData.evilIcons(61709);
  static const IconData chevronUp = FlutterIconData.evilIcons(61710);
  static const IconData clock = FlutterIconData.evilIcons(61711);
  static const IconData close = FlutterIconData.evilIcons(61712);
  static const IconData closeO = FlutterIconData.evilIcons(61713);
  static const IconData comment = FlutterIconData.evilIcons(61714);
  static const IconData creditCard = FlutterIconData.evilIcons(61715);
  static const IconData envelope = FlutterIconData.evilIcons(61716);
  static const IconData exclamation = FlutterIconData.evilIcons(61717);
  static const IconData externalLink = FlutterIconData.evilIcons(61718);
  static const IconData eye = FlutterIconData.evilIcons(61719);
  static const IconData gear = FlutterIconData.evilIcons(61720);
  static const IconData heart = FlutterIconData.evilIcons(61721);
  static const IconData image = FlutterIconData.evilIcons(61722);
  static const IconData like = FlutterIconData.evilIcons(61723);
  static const IconData link = FlutterIconData.evilIcons(61724);
  static const IconData location = FlutterIconData.evilIcons(61725);
  static const IconData lock = FlutterIconData.evilIcons(61726);
  static const IconData minus = FlutterIconData.evilIcons(61727);
  static const IconData navIcon = FlutterIconData.evilIcons(61728);
  static const IconData paperclip = FlutterIconData.evilIcons(61729);
  static const IconData pencil = FlutterIconData.evilIcons(61730);
  static const IconData play = FlutterIconData.evilIcons(61731);
  static const IconData plus = FlutterIconData.evilIcons(61732);
  static const IconData pointer = FlutterIconData.evilIcons(61733);
  static const IconData question = FlutterIconData.evilIcons(61734);
  static const IconData redo = FlutterIconData.evilIcons(61735);
  static const IconData refresh = FlutterIconData.evilIcons(61736);
  static const IconData retweet = FlutterIconData.evilIcons(61737);
  static const IconData scFacebook = FlutterIconData.evilIcons(61738);
  static const IconData scGithub = FlutterIconData.evilIcons(61739);
  static const IconData scGooglePlus = FlutterIconData.evilIcons(61740);
  static const IconData scInstagram = FlutterIconData.evilIcons(61741);
  static const IconData scLinkedin = FlutterIconData.evilIcons(61742);
  static const IconData scOdnoKlassNiki = FlutterIconData.evilIcons(61743);
  static const IconData scPinterest = FlutterIconData.evilIcons(61744);
  static const IconData scSkype = FlutterIconData.evilIcons(61745);
  static const IconData scSoundcloud = FlutterIconData.evilIcons(61746);
  static const IconData scTelegram = FlutterIconData.evilIcons(61747);
  static const IconData scTumblr = FlutterIconData.evilIcons(61748);
  static const IconData scTwitter = FlutterIconData.evilIcons(61749);
  static const IconData scVimeo = FlutterIconData.evilIcons(61750);
  static const IconData scVk = FlutterIconData.evilIcons(61751);
  static const IconData scYoutube = FlutterIconData.evilIcons(61752);
  static const IconData search = FlutterIconData.evilIcons(61753);
  static const IconData shareApple = FlutterIconData.evilIcons(61754);
  static const IconData shareGoogle = FlutterIconData.evilIcons(61755);
  static const IconData spinner = FlutterIconData.evilIcons(61756);
  static const IconData spinner_2 = FlutterIconData.evilIcons(61757);
  static const IconData spinner_3 = FlutterIconData.evilIcons(61758);
  static const IconData star = FlutterIconData.evilIcons(61759);
  static const IconData tag = FlutterIconData.evilIcons(61760);
  static const IconData trash = FlutterIconData.evilIcons(61761);
  static const IconData trophy = FlutterIconData.evilIcons(61762);
  static const IconData undo = FlutterIconData.evilIcons(61763);
  static const IconData unlock = FlutterIconData.evilIcons(61764);
  static const IconData user = FlutterIconData.evilIcons(61765);
}
