import 'package:flutter/material.dart';

import 'flutter_icon_data.dart';

/// A class that holds static variables representing all Icons under SimpleLineIcons
///
/// https://simplelineicons.github.io/
class SimpleLineIcons {
  SimpleLineIcons._();
  static const IconData user = FlutterIconData.simpleLineIcons(57349);
  static const IconData people = FlutterIconData.simpleLineIcons(57345);
  static const IconData userFemale = FlutterIconData.simpleLineIcons(57344);
  static const IconData userFollow = FlutterIconData.simpleLineIcons(57346);
  static const IconData userFollowing = FlutterIconData.simpleLineIcons(57347);
  static const IconData userUnfollow = FlutterIconData.simpleLineIcons(57348);
  static const IconData login = FlutterIconData.simpleLineIcons(57446);
  static const IconData logout = FlutterIconData.simpleLineIcons(57445);
  static const IconData emojiSmile = FlutterIconData.simpleLineIcons(57377);
  static const IconData phone = FlutterIconData.simpleLineIcons(58880);
  static const IconData callEnd = FlutterIconData.simpleLineIcons(57416);
  static const IconData callIn = FlutterIconData.simpleLineIcons(57415);
  static const IconData callOut = FlutterIconData.simpleLineIcons(57414);
  static const IconData map = FlutterIconData.simpleLineIcons(57395);
  static const IconData locationPin = FlutterIconData.simpleLineIcons(57494);
  static const IconData direction = FlutterIconData.simpleLineIcons(57410);
  static const IconData directions = FlutterIconData.simpleLineIcons(57409);
  static const IconData compass = FlutterIconData.simpleLineIcons(57413);
  static const IconData layers = FlutterIconData.simpleLineIcons(57396);
  static const IconData menu = FlutterIconData.simpleLineIcons(58881);
  static const IconData list = FlutterIconData.simpleLineIcons(57447);
  static const IconData optionsVertical =
      FlutterIconData.simpleLineIcons(58882);
  static const IconData options = FlutterIconData.simpleLineIcons(58883);
  static const IconData arrowDown = FlutterIconData.simpleLineIcons(58884);
  static const IconData arrowLeft = FlutterIconData.simpleLineIcons(58885);
  static const IconData arrowRight = FlutterIconData.simpleLineIcons(58886);
  static const IconData arrowUp = FlutterIconData.simpleLineIcons(58887);
  static const IconData arrowUpCircle = FlutterIconData.simpleLineIcons(57464);
  static const IconData arrowLeftCircle =
      FlutterIconData.simpleLineIcons(57466);
  static const IconData arrowRightCircle =
      FlutterIconData.simpleLineIcons(57465);
  static const IconData arrowDownCircle =
      FlutterIconData.simpleLineIcons(57467);
  static const IconData check = FlutterIconData.simpleLineIcons(57472);
  static const IconData clock = FlutterIconData.simpleLineIcons(57473);
  static const IconData plus = FlutterIconData.simpleLineIcons(57493);
  static const IconData minus = FlutterIconData.simpleLineIcons(58901);
  static const IconData close = FlutterIconData.simpleLineIcons(57474);
  static const IconData event = FlutterIconData.simpleLineIcons(58905);
  static const IconData exclamation = FlutterIconData.simpleLineIcons(58903);
  static const IconData organization = FlutterIconData.simpleLineIcons(58902);
  static const IconData trophy = FlutterIconData.simpleLineIcons(57350);
  static const IconData screenSmartphone =
      FlutterIconData.simpleLineIcons(57360);
  static const IconData screenDesktop = FlutterIconData.simpleLineIcons(57361);
  static const IconData plane = FlutterIconData.simpleLineIcons(57362);
  static const IconData notebook = FlutterIconData.simpleLineIcons(57363);
  static const IconData mustache = FlutterIconData.simpleLineIcons(57364);
  static const IconData mouse = FlutterIconData.simpleLineIcons(57365);
  static const IconData magnet = FlutterIconData.simpleLineIcons(57366);
  static const IconData energy = FlutterIconData.simpleLineIcons(57376);
  static const IconData disc = FlutterIconData.simpleLineIcons(57378);
  static const IconData cursor = FlutterIconData.simpleLineIcons(57454);
  static const IconData cursorMove = FlutterIconData.simpleLineIcons(57379);
  static const IconData crop = FlutterIconData.simpleLineIcons(57380);
  static const IconData chemistry = FlutterIconData.simpleLineIcons(57382);
  static const IconData speedometer = FlutterIconData.simpleLineIcons(57351);
  static const IconData shield = FlutterIconData.simpleLineIcons(57358);
  static const IconData screenTablet = FlutterIconData.simpleLineIcons(57359);
  static const IconData magicWand = FlutterIconData.simpleLineIcons(57367);
  static const IconData hourglass = FlutterIconData.simpleLineIcons(57368);
  static const IconData graduation = FlutterIconData.simpleLineIcons(57369);
  static const IconData ghost = FlutterIconData.simpleLineIcons(57370);
  static const IconData gameController = FlutterIconData.simpleLineIcons(57371);
  static const IconData fire = FlutterIconData.simpleLineIcons(57372);
  static const IconData eyeglass = FlutterIconData.simpleLineIcons(57373);
  static const IconData envelopeOpen = FlutterIconData.simpleLineIcons(57374);
  static const IconData envelopeLetter = FlutterIconData.simpleLineIcons(57375);
  static const IconData bell = FlutterIconData.simpleLineIcons(57383);
  static const IconData badge = FlutterIconData.simpleLineIcons(57384);
  static const IconData anchor = FlutterIconData.simpleLineIcons(57385);
  static const IconData wallet = FlutterIconData.simpleLineIcons(57386);
  static const IconData vector = FlutterIconData.simpleLineIcons(57387);
  static const IconData speech = FlutterIconData.simpleLineIcons(57388);
  static const IconData puzzle = FlutterIconData.simpleLineIcons(57389);
  static const IconData printer = FlutterIconData.simpleLineIcons(57390);
  static const IconData present = FlutterIconData.simpleLineIcons(57391);
  static const IconData playlist = FlutterIconData.simpleLineIcons(57392);
  static const IconData pin = FlutterIconData.simpleLineIcons(57393);
  static const IconData picture = FlutterIconData.simpleLineIcons(57394);
  static const IconData handbag = FlutterIconData.simpleLineIcons(57397);
  static const IconData globeAlt = FlutterIconData.simpleLineIcons(57398);
  static const IconData globe = FlutterIconData.simpleLineIcons(57399);
  static const IconData folderAlt = FlutterIconData.simpleLineIcons(57401);
  static const IconData folder = FlutterIconData.simpleLineIcons(57481);
  static const IconData film = FlutterIconData.simpleLineIcons(57402);
  static const IconData feed = FlutterIconData.simpleLineIcons(57403);
  static const IconData drop = FlutterIconData.simpleLineIcons(57406);
  static const IconData drawer = FlutterIconData.simpleLineIcons(57407);
  static const IconData docs = FlutterIconData.simpleLineIcons(57408);
  static const IconData doc = FlutterIconData.simpleLineIcons(57477);
  static const IconData diamond = FlutterIconData.simpleLineIcons(57411);
  static const IconData cup = FlutterIconData.simpleLineIcons(57412);
  static const IconData calculator = FlutterIconData.simpleLineIcons(57417);
  static const IconData bubbles = FlutterIconData.simpleLineIcons(57418);
  static const IconData briefcase = FlutterIconData.simpleLineIcons(57419);
  static const IconData bookOpen = FlutterIconData.simpleLineIcons(57420);
  static const IconData basketLoaded = FlutterIconData.simpleLineIcons(57421);
  static const IconData basket = FlutterIconData.simpleLineIcons(57422);
  static const IconData bag = FlutterIconData.simpleLineIcons(57423);
  static const IconData actionUndo = FlutterIconData.simpleLineIcons(57424);
  static const IconData actionRedo = FlutterIconData.simpleLineIcons(57425);
  static const IconData wrench = FlutterIconData.simpleLineIcons(57426);
  static const IconData umbrella = FlutterIconData.simpleLineIcons(57427);
  static const IconData trash = FlutterIconData.simpleLineIcons(57428);
  static const IconData tag = FlutterIconData.simpleLineIcons(57429);
  static const IconData support = FlutterIconData.simpleLineIcons(57430);
  static const IconData frame = FlutterIconData.simpleLineIcons(57400);
  static const IconData sizeFullscreen = FlutterIconData.simpleLineIcons(57431);
  static const IconData sizeActual = FlutterIconData.simpleLineIcons(57432);
  static const IconData shuffle = FlutterIconData.simpleLineIcons(57433);
  static const IconData shareAlt = FlutterIconData.simpleLineIcons(57434);
  static const IconData share = FlutterIconData.simpleLineIcons(57435);
  static const IconData rocket = FlutterIconData.simpleLineIcons(57436);
  static const IconData question = FlutterIconData.simpleLineIcons(57437);
  static const IconData pieChart = FlutterIconData.simpleLineIcons(57438);
  static const IconData pencil = FlutterIconData.simpleLineIcons(57439);
  static const IconData note = FlutterIconData.simpleLineIcons(57440);
  static const IconData loop = FlutterIconData.simpleLineIcons(57444);
  static const IconData home = FlutterIconData.simpleLineIcons(57449);
  static const IconData grid = FlutterIconData.simpleLineIcons(57450);
  static const IconData graph = FlutterIconData.simpleLineIcons(57451);
  static const IconData microphone = FlutterIconData.simpleLineIcons(57443);
  static const IconData musicToneAlt = FlutterIconData.simpleLineIcons(57441);
  static const IconData musicTone = FlutterIconData.simpleLineIcons(57442);
  static const IconData earphonesAlt = FlutterIconData.simpleLineIcons(57404);
  static const IconData earphones = FlutterIconData.simpleLineIcons(57405);
  static const IconData equalizer = FlutterIconData.simpleLineIcons(57452);
  static const IconData like = FlutterIconData.simpleLineIcons(57448);
  static const IconData dislike = FlutterIconData.simpleLineIcons(57453);
  static const IconData controlStart = FlutterIconData.simpleLineIcons(57455);
  static const IconData controlRewind = FlutterIconData.simpleLineIcons(57456);
  static const IconData controlPlay = FlutterIconData.simpleLineIcons(57457);
  static const IconData controlPause = FlutterIconData.simpleLineIcons(57458);
  static const IconData controlForward = FlutterIconData.simpleLineIcons(57459);
  static const IconData controlEnd = FlutterIconData.simpleLineIcons(57460);
  static const IconData volume_1 = FlutterIconData.simpleLineIcons(57503);
  static const IconData volume_2 = FlutterIconData.simpleLineIcons(57504);
  static const IconData volumeOff = FlutterIconData.simpleLineIcons(57505);
  static const IconData calendar = FlutterIconData.simpleLineIcons(57461);
  static const IconData bulb = FlutterIconData.simpleLineIcons(57462);
  static const IconData chart = FlutterIconData.simpleLineIcons(57463);
  static const IconData ban = FlutterIconData.simpleLineIcons(57468);
  static const IconData bubble = FlutterIconData.simpleLineIcons(57469);
  static const IconData camRecorder = FlutterIconData.simpleLineIcons(57470);
  static const IconData camera = FlutterIconData.simpleLineIcons(57471);
  static const IconData cloudDownload = FlutterIconData.simpleLineIcons(57475);
  static const IconData cloudUpload = FlutterIconData.simpleLineIcons(57476);
  static const IconData envelope = FlutterIconData.simpleLineIcons(57478);
  static const IconData eye = FlutterIconData.simpleLineIcons(57479);
  static const IconData flag = FlutterIconData.simpleLineIcons(57480);
  static const IconData heart = FlutterIconData.simpleLineIcons(57482);
  static const IconData info = FlutterIconData.simpleLineIcons(57483);
  static const IconData key = FlutterIconData.simpleLineIcons(57484);
  static const IconData link = FlutterIconData.simpleLineIcons(57485);
  static const IconData lock = FlutterIconData.simpleLineIcons(57486);
  static const IconData lockOpen = FlutterIconData.simpleLineIcons(57487);
  static const IconData magnifier = FlutterIconData.simpleLineIcons(57488);
  static const IconData magnifierAdd = FlutterIconData.simpleLineIcons(57489);
  static const IconData magnifierRemove =
      FlutterIconData.simpleLineIcons(57490);
  static const IconData paperClip = FlutterIconData.simpleLineIcons(57491);
  static const IconData paperPlane = FlutterIconData.simpleLineIcons(57492);
  static const IconData power = FlutterIconData.simpleLineIcons(57495);
  static const IconData refresh = FlutterIconData.simpleLineIcons(57496);
  static const IconData reload = FlutterIconData.simpleLineIcons(57497);
  static const IconData settings = FlutterIconData.simpleLineIcons(57498);
  static const IconData star = FlutterIconData.simpleLineIcons(57499);
  static const IconData symbolFemale = FlutterIconData.simpleLineIcons(57500);
  static const IconData symbolMale = FlutterIconData.simpleLineIcons(57501);
  static const IconData target = FlutterIconData.simpleLineIcons(57502);
  static const IconData creditCard = FlutterIconData.simpleLineIcons(57381);
  static const IconData paypal = FlutterIconData.simpleLineIcons(58888);
  static const IconData socialTumblr = FlutterIconData.simpleLineIcons(57354);
  static const IconData socialTwitter = FlutterIconData.simpleLineIcons(57353);
  static const IconData socialFacebook = FlutterIconData.simpleLineIcons(57355);
  static const IconData socialInstagram =
      FlutterIconData.simpleLineIcons(58889);
  static const IconData socialLinkedin = FlutterIconData.simpleLineIcons(58890);
  static const IconData socialPinterest =
      FlutterIconData.simpleLineIcons(58891);
  static const IconData socialGithub = FlutterIconData.simpleLineIcons(58892);
  static const IconData socialGoogle = FlutterIconData.simpleLineIcons(58893);
  static const IconData socialReddit = FlutterIconData.simpleLineIcons(58894);
  static const IconData socialSkype = FlutterIconData.simpleLineIcons(58895);
  static const IconData socialDribbble = FlutterIconData.simpleLineIcons(57357);
  static const IconData socialBehance = FlutterIconData.simpleLineIcons(58896);
  static const IconData socialFourSquare =
      FlutterIconData.simpleLineIcons(58897);
  static const IconData socialSoundcloud =
      FlutterIconData.simpleLineIcons(58898);
  static const IconData socialSpotify = FlutterIconData.simpleLineIcons(58899);
  static const IconData socialStumbleUpon =
      FlutterIconData.simpleLineIcons(58900);
  static const IconData socialYoutube = FlutterIconData.simpleLineIcons(57352);
  static const IconData socialDropbox = FlutterIconData.simpleLineIcons(57356);
  static const IconData socialVkontakte =
      FlutterIconData.simpleLineIcons(58904);
  static const IconData socialSteam = FlutterIconData.simpleLineIcons(58912);
}
